### PR TITLE
Fetch community projects from GitHub

### PR DESCRIPTION
**Pull request by cmfcmf**
I have started to work on automatically fetching GitHub repositories with the topic `padauk` and displaying them. This requires using GitHub Actions to build the site, since we are now using custom plugins not available on GitHub Pages by default.

image

Note that there is at least one false positive. Maybe we should use a more specific tag than `padauk`?
This is the GitHub search I'm currently executing: https://github.com/search?q=topic%3Apadauk%20-user%3Afree-pdk%20archived%3Afalse%20sort%3Aupdated

We can also list projects using a specific µC by searching for repos with the `padauk` and, for example, `PFS173` tag on the µC details page.

You can see a working run of the GitHub Action here: https://github.com/cmfcmf/free-pdk.github.io/runs/848993718?check_suite_focus=true

You will have to execute `bundle install` to update to the new dependency versions if you try this locally.

### CODE REVIEW

**Comment by cmfcmf** [comment]
This PR is now ready for review.

**Review by cpldcpu — APPROVED** [review]

**Comment by cpldcpu** [comment]
This looks awesome!

Maybe a search for specific controller types would yield more accurate results? e.g. PFS173, PFS154 and so on?  Or would it make sense to manually maintain an exclusion list? The one false positive is a bit confusing.

"Padauk" is a actually a type of wood. Luckily there are not many woodworking projects on Github, but who knows...

**Comment by cpldcpu** [comment]
Btw, what does it take to set up the github action? I am just looking at the documentation.

**Comment by cmfcmf** [comment]
> Btw, what does it take to set up the github action? I am just looking at the documentation.

The action will "just work" (hopefully :see_no_evil:) as soon as this is merged into master.

> Maybe a search for specific controller types would yield more accurate results? e.g. PFS173, PFS154 and so on? Or would it make sense to manually maintain an exclusion list? The one false positive is a bit confusing.

> "Padauk" is a actually a type of wood. Luckily there are not many woodworking projects on Github, but who knows...

Maybe we could change the topic to `padauk-mikrocontroller`?

**Comment by cpldcpu** [comment]
It's a bit strange. Nothing seems to happen when I try this locally. There was  a "GithubPadaukTopics" generated in the Jekyll cache, but it does not show up on the page.

grafik

**Comment by cpldcpu** [comment]
> > Btw, what does it take to set up the github action? I am just looking at the documentation.
> 
> The action will "just work" (hopefully 🙈) as soon as this is merged into master.

Ok, I'll give it a try.
 
> > Maybe a search for specific controller types would yield more accurate results? e.g. PFS173, PFS154 and so on? Or would it make sense to manually maintain an exclusion list? The one false positive is a bit confusing.
> 
> > "Padauk" is a actually a type of wood. Luckily there are not many woodworking projects on Github, but who knows...
> 
> Maybe we could change the topic to `padauk-mikrocontroller`?

Maybe that plus tags for most used MCUs?

**Comment by cpldcpu** [comment]
I changed it to this qeury `topic:padauk -language:shell -user:free-pdk archived:false sort:updated` which excludes the one false positive. This is not a long term solution, though.

**Comment by cpldcpu** [comment]
Hm... seems that there is the same issue when deploying it on github.

**Comment by cmfcmf** [comment]
> Hm... seems that there is the same issue when deploying it on github.

You might have to change the deployed branch in the repository settings from master to gh-pages.

**Comment by cmfcmf** [comment]
> It's a bit strange. Nothing seems to happen when I try this locally. There was a "GithubPadaukTopics" generated in the Jekyll cache, but it does not show up on the page.

Have you run `bundle install` to update the dependencies? It should list "Using jekyll 4.1.1".

**Comment by cpldcpu** [comment]
> Have you run `bundle install` to update the dependencies? It should list "Using jekyll 4.1.1".

`Fetching jekyll 4.1.1
Installing jekyll 4.1.1`

Yes, looks like.

**Comment by cpldcpu** [comment]
> You might have to change the deployed branch in the repository settings from master to gh-pages.

That does not seem possible. According to some stack exchange entries this is because this is an organisation page, not a project page.

https://stackoverflow.com/questions/48244516/github-site-from-gh-pages-branch

grafik

**Comment by cmfcmf** [comment]
> That does not seem possible. According to some stack exchange entries this is because this is an organisation page, not a project page.

Oh, I didn't know that. I think we then have to rename the `master` branch to something like `production`, make that the default branch, and change the GitHub action to force push to the `master` branch instead of the `gh-pages` branch at https://github.com/free-pdk/free-pdk.github.io/blob/ddfee4750792d453d926a7d6e716b02d7bc4cf60/.github/workflows/deploy.yml#L41



> `Fetching jekyll 4.1.1 Installing jekyll 4.1.1`
> 
> Yes, looks like.

That sounds a lot like you only just upgraded to the required jekyll version. If you run `bundle install` again, it should now say `Using jekyll 4.1.1` instead of `Fetching jekyll 4.1.1 Installing jekyll 4.1.1`. Can you delete the `.jekyll-cache` and check whether it still doesn't work for you locally?

**Comment by cmfcmf** [comment]
> Oh, I didn't know that. I think we then have to rename the `master` branch to something like `production`, make that the default branch, and change the GitHub action to force push to the `master` branch instead of the `gh-pages` branch at

And also update this to `production`:
https://github.com/free-pdk/free-pdk.github.io/blob/ddfee4750792d453d926a7d6e716b02d7bc4cf60/.github/workflows/deploy.yml#L9

**Comment by cpldcpu** [comment]
oh i see, github action generated this branch:

https://github.com/free-pdk/free-pdk.github.io/tree/gh-pages

**Comment by cpldcpu** [comment]
Ok, should be changed now and github actions is committing to master:

https://github.com/free-pdk/free-pdk.github.io/tree/master

Still no project list...

**Comment by cmfcmf** [comment]
> Still no project list...

It's there! :tada: It sometimes takes a few seconds for changes to go live :)

**Comment by cpldcpu** [comment]
Yay! 🥇

**Comment by cpldcpu** [comment]
And after a reboot it also works locally. Seems that WSL2 had a major hickup in the file system.

**Comment by cpldcpu** [comment]
Btw, why should we excluse repositories from this community? could also remove the "-user:free-pdk"

**Comment by cmfcmf** [comment]
> Btw, why should we excluse repositories from this community? could also remove the "-user:free-pdk"

I felt like that was superfluous since most free-pdk repos are already mentioned further up the page. But I don't have strong feeling about that - if you think we should include them, go ahead :+1:

**Comment by cpldcpu** [comment]
ok. We can still remove the "Padauk" topic from projects that should not show up.

**Pull request merged**
