### PR TITLE
Adding page for undocumented features

### PR DESCRIPTION
**Pull request by cpldcpu**

### CODE REVIEW

**Comment by cpldcpu** [comment]
This is work in progress. The intention is to add a place to describe undocumented features. I have to admit that the wording may be a bit confusing, because many things are not documented in the Padauk MCUs. This page is for features that were intentionally disguised. Ideas are welcome...

**Comment by cpldcpu** [comment]
@cmfcmf I hope I added the image in the right place. The way I centered seems to be a bit hacky, but this is the only way I found.

In general, I was wondering whether it would be possible to add a ToC block next to the content column. Does this jeyll theme allow for this?

**Comment by cmfcmf** [comment]
It's great to see this new section! There is _so much_ information in the forum thread, but frankly, most of it is "lost" almost immediately after it is posted, since it is so unorganized and hard to discover. I know it can be a lot of work, but IMHO every extraction of information from the thread to a well structured place like this documentation is well worth it.

> @cmfcmf I hope I added the image in the right place. The way I centered seems to be a bit hacky, but this is the only way I found.

Looks fine to me 👍 
 
> In general, I was wondering whether it would be possible to add a ToC block next to the content column. Does this jeyll theme allow for this?

I assume that you think of something like done here https://reactjs.org/docs/getting-started.html (i.e., toc is always visible if the page is wide enough and scrolls with the page)?
The theme does not directly allow that, but could certainly be customized to have the toc next to the content when the screen is big enough. 

--- 

Would it make sense to also add a new section to the tutorial page that links to the undocumented features page?

**Comment by cpldcpu** [comment]
I thought in general that the index page and tutorial page is getting a bit too long and convoluted, so adding a few additional pages would make sense. Maybe there should be only an index in the tutorial that is pointing to subpages?

**Comment by cpldcpu** [comment]
I'll just merge it for now.

**Comment by cmfcmf** [comment]
> I thought in general that the index page and tutorial page is getting a bit too long and convoluted, so adding a few additional pages would make sense. Maybe there should be only an index in the tutorial that is pointing to subpages?

Sorry for not responding sooner - while I see your point, I am personally not a friend of splitting pages up until they are super long. Especially because many sections are rather short right now. I feel like the better option would be the addition of a floating menu like you proposed.

> I'll just merge it for now.

Great work :tada:

**Comment by cpldcpu** [comment]
Maybe we should switch the theme? E.g to the documentation theme or "minimal mistakes"

https://jekyllthemes.io/theme/documentation
https://mmistakes.github.io/minimal-mistakes/

**Comment by cmfcmf** [comment]
That's a good point! I like the looks and features of the minimal-mistakes theme. I have tinkered around with converting to that theme, but it still requires a bit more work. I'll get back to you once I find more time to finish it.

**Comment by cpldcpu** [comment]
I also looked into it a few weeks ago, but felt a bit lost. :) You certainly have a much better grasp of jekyll.

**Pull request merged**
