### PR TITLE
Move Padauk Links to separate column

### PR DESCRIPTION
**Pull request by serisman**

### CODE REVIEW

**Review by cmfcmf — APPROVED** [review]
Nicely done :+1:

**Comment by serisman** [comment]
Still not happy with the scrollbar on the OTP Variants:

image

Looks like the ROM column is pushing it out.

We could try and reduce the OSS Status column more somehow?  My original thought is we would have two lines, one for Easy PDK Programmer with a minimum version number, and another for SDCC with a minimum version number.  Not sure the best way to indicated all that and also reduce the space though.

Thoughts on how to fix?

**Comment by cmfcmf** [comment]
We could decrease the padding of the table cells by replacing this:
https://github.com/free-pdk/free-pdk.github.io/blob/fd4360b0001f98619ddde38c1cad9b59cdec4760/assets/main.scss#L23-L29

by this:
```scss
table {
  p {
    margin: 0;
  }

  td, th {
    text-align: center;
    padding: 10px 10px; // <-- 
  }
}
```

**Comment by serisman** [comment]
We could also make the page slightly wider.  Currently at 1040px, which still feels a little narrow to me.

Preference?

**Comment by cmfcmf** [comment]
I personally prefer the page width as it is right now.
Another option would be decreasing the font size inside tables to 14 or 15 px.

**Comment by serisman** [comment]
> I personally prefer the page width as it is right now.

I'm curious why 1040?  It is bigger than 1024 x ..., but quite a ways from the next logical size 1280 x ..., so it leaves some wider gutters.  Even just going up to 1060 fixes the scrollbar, although I think it looks even better at 1140 (and still leaves enough gutter).

> Another option would be decreasing the font size inside tables to 14 or 15 px.

I'll play around with that too.

**Comment by serisman** [comment]
Actually, simply changing the padding as you indicated looks good too.  We can just stick to that for now.

**Comment by serisman** [comment]
image

**Comment by serisman** [comment]
Hmm... the preview site looks ok, but the production site isn't applying the padding override.  Any ideas?

EDIT:  looks like my browser was caching the css.  A clear cache / hard reload fixed it for me.

**Comment by cpldcpu** [comment]
I would suggest to use a `&nbsp;`  for "product page" to avoid linebreaking.

**Pull request merged**
