### PR TITLE
Expand pinout diagrams to their full height

### PR DESCRIPTION
**Pull request by cmfcmf**

### CODE REVIEW

**Comment by cpldcpu** [comment]
Would it also be an option to center the diagrams? They are currently left aligned, which looks a bit untidy, as already remarked by @serisman.

**Comment by cmfcmf** [comment]
I tried that, but it broke the "download image" buttons. It's on my TODO list to find a solution though.

**Comment by cmfcmf** [comment]
Oh, I just noticed that I targeted this PR to the master branch :see_no_evil:

**Comment by cpldcpu** [comment]
> Oh, I just noticed that I targeted this PR to the master branch 🙈

oops - thats why i did not notice any difference when i pulled develop :)

**Comment by cpldcpu** [comment]
Looking at the state right now, centering would REALLY improve it :)

Another idea: how about making "Maximum Sink/Drive Current" and maybe "pull up/pull down" unselected by default? This results in much sleeker diagrams. People can still enable it.

**Comment by cmfcmf** [comment]
> Another idea: how about making "Maximum Sink/Drive Current" and maybe "pull up/pull down" unselected by default? This results in much sleeker diagrams. People can still enable it.

Done :tada:

**Pull request merged**
