### PR TITLE
Fix incorrect message aboug using Padauk custom 'C' along with EasyPdkProg

### PR DESCRIPTION
**Pull request by serisman**

### CODE REVIEW

**Comment by cmfcmf** [comment]
Whoops, seems like I mixed something up. Thank you for correcting it :+1:

**Comment by cpldcpu** [comment]
I changed this section a bit more. Please check if these retains your message:

https://github.com/free-pdk/free-pdk.github.io/commit/d1acf6a07e904b75dc46e1d0b0a3197f469e507b

**Comment by serisman** [comment]
Overall looks pretty good.  I left a few comments on the commit.

**Comment by cpldcpu** [comment]
Update addressing your comments:

https://github.com/free-pdk/free-pdk.github.io/commit/a9609817b44272f71caac8076e845127fb6aa6d2

**Comment by serisman** [comment]
Looks pretty good.

Did you decide not to split this into two paragraphs?
```
The open source tool-chain is based on the Small Device C-Compiler (SDCC) and therefore does support Standard C and common binary output formats (intel hex and bin), including those used by the Easy PDK Programmer. Please note that right now there is no interchangeability between both tool-chains. Binaries generated by SDCC cannot be written by the official Padauk programmer, but only by the Easy PDK Programmer.
```
->
```
The open source tool-chain is based on the Small Device C-Compiler (SDCC) and therefore does support Standard C and common binary output formats (intel hex and bin), including those used by the Easy PDK Programmer.

Please note that right now there is no interchangeability between both tool-chains. Binaries generated by SDCC cannot be written by the official Padauk programmer, but only by the Easy PDK Programmer.
```

**Comment by cpldcpu** [comment]
Closing this pull request to avoid too much confusion. Everything has been added.

**Pull request closed without merging**
